initFields:
  homepage: "https://sceneforge.org/"
  license: CC0
  repository:
    directory: packages/
    type: git
    url: "https://github.com/sceneforge/sceneforge.git"

initScope: sceneforge

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs
