cacheFolder: ./.yarn/cache

checksumBehavior: throw

cloneConcurrency: 8

enableColors: true

enableStrictSsl: true

enableTransparentWorkspaces: true

globalFolder: ./.yarn/global

nmMode: hardlinks-local

nodeLinker: pnp

pnpEnableEsmLoader: true

pnpMode: strict

pnpShebang: "#!/usr/bin/env node"

pnpUnpluggedFolder: ./.yarn/unplugged

virtualFolder: ./.yarn/__virtual__

yarnPath: .yarn/releases/yarn-4.1.0.cjs
