name: Build

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'build'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Build
        run: yarn build
            
      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: sceneforge-docs
          path: ./apps/docs/dist

      - name: Upload App Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: sceneforge-app
          path: ./apps/sceneforge/dist
      
      - name: Docs Deployment
        run: gh workflow run publish.yml -F run_id=${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: docs
          BRANCH: main
