name: Build

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'build'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
            
      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: sceneforge-docs
          path: ./apps/docs/dist

      - name: Upload App Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: sceneforge-app
          path: ./apps/sceneforge/dist

      # - name: Trigger Docs Publish
      #   run: gh workflow run publish.yml -R $GH_REPO -F run-id=${{ github.run_id }}
      #   env:
      #     GH_REPO: ${{ github.repository_owner }}/docs
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
