name: Deploy static content to Pages

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID of the build workflow"
        required: true
        type: number

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download App Artifact
        uses: actions/download-artifact@v4
        with:
          name: sceneforge-app
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ inputs.run_id }}
          path: ${{ github.workspace }}/dist
        
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/dist
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
