name: Production Workflow

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  basic:
    name: 'Lint, Test and Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      
      - name: Install Dependencies
        run: yarn install --immutable
      
      - name: Lint all Packages
        run: yarn lint:all
      
      - name: Build
        run: yarn build
      
      - name: Compress App Artifact
        run: tar -C apps/sceneforge/dist -cvzf sceneforge.tar.gz .
      
      - name: Compress Docs Artifact
        run: tar -C apps/docs/dist -cvzf docs.tar.gz .

      - name: 'Create Release'
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            sceneforge.tar.gz
            docs.tar.gz
